name: Test

on:
  pull_request:
  push:
    tags:
      - v*
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.20.x
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Download Go modules
        run: go mod download
        env:
          GOPROXY: https://proxy.golang.org

      - name: Build
        run: go build -o ./tmp/main -v main.go

      - name: Test
        run: |
          mkdir -p ./build/coverage
          go test -coverprofile=./build/coverage/cover.out -cover ./...
          go tool cover -func=./build/coverage/cover.out
